// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Negocio.Bdata.Data;

#nullable disable

namespace Negocio.Bdata.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231029235700_inicalq1q29")]
    partial class inicalq1q29
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idventa")
                        .HasColumnType("int");

                    b.Property<string>("Numero_cuotas")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("Ventaid")
                        .HasColumnType("int");

                    b.Property<int>("dnipersona")
                        .HasColumnType("int");

                    b.Property<string>("total")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Ventaid");

                    b.ToTable("cuotas");
                });

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Personas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DNI" }, "Persona_DNI_UQ")
                        .IsUnique();

                    b.ToTable("personas");
                });

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Venta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Idpersona")
                        .HasColumnType("int");

                    b.Property<int?>("PersonasId")
                        .HasColumnType("int");

                    b.Property<string>("Saldo_Total")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.HasIndex("PersonasId");

                    b.ToTable("ventas");
                });

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Cuota", b =>
                {
                    b.HasOne("Negocio.Bdata.Data.Entity.Venta", null)
                        .WithMany("cuotas")
                        .HasForeignKey("Ventaid");
                });

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Venta", b =>
                {
                    b.HasOne("Negocio.Bdata.Data.Entity.Personas", null)
                        .WithMany("ventas")
                        .HasForeignKey("PersonasId");
                });

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Personas", b =>
                {
                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Negocio.Bdata.Data.Entity.Venta", b =>
                {
                    b.Navigation("cuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
